### ISSUE TITLE
Connection refused when kafka connect hits zeebe

### ISSUE THREAD

**Issue by shubham49** [zeebe-io/kafka-connect-zeebe#50]
I am using same docker compose file on my mac and getting below error at kafka connect while creating source connector

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:26500
2020-11-02T06:44:12.537124900Z Caused by: java.net.ConnectException: Connection refused
2020-11-02T06:44:12.537149800Z 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2020-11-02T06:44:12.537174400Z 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
2020-11-02T06:44:12.537199000Z 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
2020-11-02T06:44:12.537237900Z 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2020-11-02T06:44:12.537264900Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
2020-11-02T06:44:12.537290000Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2020-11-02T06:44:12.537309000Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2020-11-02T06:44:12.537325900Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2020-11-02T06:44:12.537392500Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-11-02T06:44:12.537435100Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-11-02T06:44:12.537466600Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-11-02T06:44:12.537497100Z 	at java.lang.Thread.run(Thread.java:748)

**Comment by shubham49** [comment]
I was running zeebe on my local so while creating source connector I had to uncomment property key from __zeebe.client.broker.contactPoint to zeebe.client.broker.contactPoint
